[package]
name = "cryptonite"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.10.2"
hex = "0.4.3"
rand= "0.8.5"
ring = "0.16.20"
clap = "2.33.3"
num-traits = "0.2.15"
